cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'homebrew/binary'
tap 'homebrew/core'
tap 'homebrew/fuse'
tap 'homebrew/php'
tap 'homebrew/python'
tap 'homebrew/versions'
tap 'homebrew/boneyard'
brew 'mas'
brew 'openssl'
brew 'gcc'
brew 'coreutils'
brew 'lame'
brew 'x264'
brew 'xvid'
brew 'faac'
brew 'libvorbis'
brew 'ffmpeg', args: ['with-faac']
brew 'pcre'
brew 'gettext'
brew 'git'
brew 'git-extras'
brew 'go'
brew 'hub'
brew 'jpeg'
brew 'libpng'
brew 'libtiff'
brew 'freetype'
brew 'little-cms'
brew 'little-cms2'
brew 'webp'
brew 'imagemagick', args: ['with-little-cms', 'with-little-cms2']
brew 'libmemcached'
brew 'memcached'
brew 'readline'
brew 'sqlite'
brew 'gdbm'
brew 'sphinx-doc'
brew 'python'
brew 'python3'
brew 'mercurial'
brew 'autoconf'
brew 'pyenv'
brew 'node'
brew 'libffi'
brew 'ssh-copy-id'
brew 'wget'
brew 'rtmpdump'
brew 'youtube-dl'
brew 'texi2html'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'amazon-music'
cask 'appcleaner'
cask 'atom'
cask 'audio-hijack'
cask 'bartender'
cask 'dropbox'
cask 'firefox'
cask 'free-ruler'
cask 'google-drive'
cask 'gpgtools'
cask 'iterm2'
cask 'mamp'
cask 'moom'
cask 'multifirefox'
cask 'openoffice'
cask 'seil'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'tower'
cask 'transmit'
cask 'vagrant'
cask 'virtualbox'

mas 'Airmail 3', id: 918858936
mas 'Better', id: 1121192229
mas 'Deckset', id: 847496013
mas 'djay Pro', id: 947578651
mas 'iA Writer', id: 775737590
mas 'iPhoto', id: 408981381
mas 'Keynote', id: 409183694
mas 'Kuvva', id: 451557061
mas 'Moom', id: 419330170
mas 'Numbers', id: 409203825
mas 'Pixelmator', id: 407963104
mas 'unDock', id: 402359583
mas 'xScope', id: 447661441
